part of '../non3d_editors.dart';

extension _BlenderDopeSheetEditorHeaderMenus on BlenderDopeSheetEditorHeader {
  Map<String, List<String>> get _menuItems => <String, List<String>>{
    'View': _timeline
        ? const <String>[
            'Show Region UI',
            'Show Region HUD',
            'Show Region Channels',
            'Playback Controls',
            'Frame All',
            'Frame Scene Range',
            'View Frame',
            'Show Markers',
            'Show Seconds',
            'Show Locked Time',
            'Show Only Selected',
            'Show Errors',
            'Cache',
            'Area',
          ]
        : const <String>[
            'Show Region UI',
            'Show Region HUD',
            'Show Region Channels',
            'Playback Controls',
            'View Selected',
            'View All',
            'Frame Scene Range',
            'View Frame',
            'Multi-Word Match Search',
            'Realtime Update',
            'Show Sliders',
            'Show Interpolation',
            'Show Extremes',
            'Auto Merge Keyframes',
            'Show Markers',
            'Show Seconds',
            'Show Locked Time',
            'Set Preview Range',
            'Clear Preview Range',
            'Toggle Graph Editor',
            'Cache',
            'Area',
          ],
    'Marker': const <String>[
      'Lock Markers',
      'Jump to Previous Marker',
      'Jump to Next Marker',
      'Bind Camera to Marker',
      'Select Marker',
      'Move Marker',
      'Rename Marker',
      'Delete Marker',
      'Duplicate Marker',
      'Add Marker',
    ],
    'Select': const <String>[
      'All',
      'None',
      'Invert',
      'Box Select',
      'Box Select (Axis Range)',
      'Circle Select',
      'Lasso Select',
      'More',
      'Less',
      'Select Linked',
      'Select by Type',
      'Columns on Selected Keys',
      'Before Current Frame',
      'After Current Frame',
    ],
    'Channel': const <String>[
      'Delete Channels',
      'Clean Channels',
      'Group Channels',
      'Ungroup Channels',
      'Toggle Channel Setting',
      'Enable Channel Setting',
      'Disable Channel Setting',
      'Toggle Editable',
      'Extrapolation Mode',
      'Expand Channels',
      'Collapse Channels',
      'Move Channels',
      'Bake Channels',
      'View Selected Channels',
    ],
    'Key': const <String>[
      'Transform',
      'Mirror',
      'Snap',
      'Jump to Selected',
      'Copy',
      'Paste',
      'Paste Flipped',
      'Insert Keyframe',
      'Duplicate',
      'Keyframe Type',
      'Handle Type',
      'Interpolation Mode',
      'Easing Mode',
      'Clean Keyframes',
      'Bake Keyframes',
      'Discontinuity (Euler) Filter',
      'Delete',
    ],
    'Action': const <String>[
      'Merge Animation',
      'Separate Slots',
      'Replace Action',
      'Replace Action New',
      'Replace Action Duplicate',
      'Move Channels to New Action',
      'Push Down Action',
      'Stash Action',
    ],
  };
}
