part of '../non3d_editors.dart';

extension _BlenderSequencerEditorHeaderMenus on BlenderSequencerEditorHeader {
  Map<String, List<String>> get _menuItems => <String, List<String>>{
    'View': <String>[
      'Show Region Toolbar',
      'Show Region UI',
      'Show Tool Header',
      if (_sequencerView) 'Show Region HUD',
      if (_sequencerView) 'Show Region Channels',
      'Playback Controls',
      if (_preview) 'Preview During Transform',
      'Refresh All',
      'Frame Selected',
      if (_sequencerView) ...<String>[
        'View All',
        'Frame Preview Range',
        'View Frame',
        'Clamp View',
      ],
      if (_preview) ...<String>[
        'Fit Preview in Window',
        'Preview Zoom',
        'Auto Zoom',
        'Proxy',
      ],
      'Show Seconds',
      if (_sequencerView) ...<String>[
        'Show Markers',
        'Show Locked Time',
        'Navigation',
        'Range',
      ],
      'Render Still Preview',
      'Render Sequence Preview',
      'Export Subtitles',
      'Toggle Sequencer/Preview',
      'Area',
    ],
    'Select': <String>[
      'All',
      'None',
      'Invert',
      'Box Select',
      if (_sequencerView) 'Box Select (Include Handles)',
      if (_sequencerView) ...<String>['More', 'Less'],
      'Select All by Type',
      'Select Grouped',
      if (_sequencerView) ...<String>[
        'Select Linked',
        'Side of Frame',
        'Handle',
        'Channel',
      ],
    ],
    'Marker': const <String>[
      'Lock Markers',
      'Jump to Previous Marker',
      'Jump to Next Marker',
      'Bind Camera to Marker',
      'Select Marker',
      'Move Marker',
      'Rename Marker',
      'Delete Marker',
      'Duplicate Marker',
      'Add Marker',
    ],
    'Add': const <String>[
      'Search...',
      'Scene',
      'Clip',
      'Mask',
      'Movie...',
      'Sound...',
      'Image/Sequence...',
      'Color',
      'Text',
      'Adjustment Layer',
      'Compositor',
      'Scene Strip',
      'Transition',
      'Wipe',
      'Glow',
      'Transform',
      'Speed',
    ],
    'Strip': <String>[
      'Transform',
      if (_preview) ...<String>[
        'Mirror',
        'Copy',
        'Paste',
        'Duplicate',
        'Animation',
        'Show/Hide',
        'Text',
      ],
      if (_sequencerView) ...<String>[
        'Retiming',
        'Split',
        'Hold Split',
        'Duplicate Linked',
        'Modifiers',
        'Meta',
        'Color Tag',
        'Lock/Mute',
        'Connect',
        'Input',
      ],
      'Ripple Delete',
      'Delete',
    ],
    'Image': const <String>[
      'Transform',
      'Clear',
      'Apply',
      'Scale To Fit',
      'Scale to Fill',
      'Stretch To Fill',
    ],
  };
}
